import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './styles/globals.css';

const nunito = Nunito_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Admparafusos',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className="w-full h-full">
      <body className={nunito.className + ' w-full h-full'}>{children}</body>
    </html>
  );
}
